#ifndef bidrectional_packets_h
#define bidrectional_packets_h

#include "Packet0x0C.hpp"
#include "Packet0x15.hpp"
#include "Packet0x22.hpp"
#include "Packet0x2C.hpp"
#include "Packet0x39.hpp"
#include "Packet0x3A.hpp"
#include "Packet0x56.hpp"
#include "Packet0x66.hpp"
#include "Packet0x6C.hpp"
#include "Packet0x6F.hpp"
#include "Packet0x71.hpp"
#include "Packet0x72.hpp"
#include "Packet0x73.hpp"
#include "Packet0x93.hpp"
#include "Packet0x95.hpp"
#include "Packet0x98.hpp"
#include "Packet0x99.hpp"
#include "Packet0x9A.hpp"
#include "Packet0xB8.hpp"
#include "Packet0xBB.hpp"
#include "Packet0xBD.hpp"
#include "Packet0xBE.hpp"
#include "Packet0xBF.hpp"
#include "Packet0xC2.hpp"
#include "Packet0xC8.hpp"
#include "Packet0xC9.hpp"
#include "Packet0xCA.hpp"
#include "Packet0xD0.hpp"
#include "Packet0xD1.hpp"
#include "Packet0xD4.hpp"
#include "Packet0xD6.hpp"
#include "Packet0xD7.hpp"
#include "Packet0xF1.hpp"

#endif

