// 
// Created on:  6/5/21

#ifndef packet_sizes_h
#define packet_sizes_h
const std::map<unsigned char, packet_lookup> Packet::_packet_info = {
	// <----------------------Incoming---------------------------
	{0x00,packet_lookup("Create Character",0x0068)},
	{0x01,packet_lookup("Disconnect Notification",0xffff)},
	{0x02,packet_lookup("Move Request",0x0007)},
	{0x03,packet_lookup("Talk Request",0xffff)},
	{0x04,packet_lookup("Request GOD Mode (GOD Client)",0x0002)},
	{0x05,packet_lookup("Request Attack",0x0005)},
	{0x06,packet_lookup("Double Click",0x0005)},
	{0x07,packet_lookup("Pickup Item",0x0007)},
	{0x08,packet_lookup("Drop Item",0x000f)},
	{0x09,packet_lookup("Single Click",0x0005)},
	{0x0a,packet_lookup("Edit (God Client)",0x000b)},
	{0x12,packet_lookup("Request Skill (etc. use)",0xffff)},
	{0x13,packet_lookup("Drop -> Wear Item",0x000d)},
	{0x14,packet_lookup("Send Elevation (GOD Client)",0x0006)},
	{0x1e,packet_lookup("Control Animation",0x0004)},
	{0x34,packet_lookup("Get Player Status",0x000a)},
	{0x35,packet_lookup("Add Resource (GOD Client)",0x028d)},
	{0x37,packet_lookup("Move Item (GOD Client)",0x0008)},
	{0x38,packet_lookup("Pathfinding in Client",0x0007)},
	{0x3b,packet_lookup("Buy Item(s)",0xffff)},
	{0x45,packet_lookup("Version OK",0x002d)},
	{0x46,packet_lookup("New Artwork",0xffff)},
	{0x47,packet_lookup("New Terrain",0x000b)},
	{0x48,packet_lookup("New Animation",0x0049)},
	{0x49,packet_lookup("New Hues",0x005d)},
	{0x4a,packet_lookup("Delete Art",0x0005)},
	{0x4b,packet_lookup("Check Client Version",0x0009)},
	{0x4c,packet_lookup("Script Names",0xffff)},
	{0x4d,packet_lookup("Edit Script File",0xffff)},
	{0x50,packet_lookup("Board Header",0xffff)},
	{0x51,packet_lookup("Board Message",0xffff)},
	{0x52,packet_lookup("Board Post Message",0xffff)},
	{0x57,packet_lookup("Update Region",0x006e)},
	{0x58,packet_lookup("Add Region",0x006a)},
	{0x59,packet_lookup("New Context FX",0xffff)},
	{0x5a,packet_lookup("Update Context FX",0xffff)},
	{0x5b,packet_lookup("Time",0x0004)},
	{0x5c,packet_lookup("Restart Version",0x0002)},
	{0x5d,packet_lookup("Login Character",0x0049)},
	{0x5e,packet_lookup("Server Listing",0xffff)},
	{0x5f,packet_lookup("Server List Add Entry",0x0031)},
	{0x60,packet_lookup("Server List Remove Entry",0x0005)},
	{0x61,packet_lookup("Remove Static Object",0x0009)},
	{0x62,packet_lookup("Move Static Object",0x000f)},
	{0x63,packet_lookup("Load Area",0x000d)},
	{0x64,packet_lookup("Load Area Request",0x0001)},
	{0x69,packet_lookup("Change Text/Emote Colors",0x0005)},
	{0x75,packet_lookup("Rename Character",0x0023)},
	{0x7d,packet_lookup("Response To Dialog Box",0x000d)},
	{0x80,packet_lookup("Login Request",0x003e)},
	{0x83,packet_lookup("Delete Character",0x0027)},
	{0x8d,packet_lookup("Character Creation (KR +SA 3D clients only",0x0092)},
	{0x91,packet_lookup("Game Server Login",0x0041)},
	{0x9b,packet_lookup("Request Help",0x0102)},
	{0x9f,packet_lookup("Sell List Reply",0xffff)},
	{0xa0,packet_lookup("Select Server",0x0003)},
	{0xa4,packet_lookup("Client Spy",0xffff)},
	{0xac,packet_lookup("Gump Text Entry Dialog Reply",0xffff)},
	{0xad,packet_lookup("Unicode/ASCII speech request",0xffff)},
	{0xb1,packet_lookup("Gump Menu Selection",0xffff)},
	{0xb3,packet_lookup("Chat Text",0xffff)},
	{0xb5,packet_lookup("Open Chat Window",0x0040)},
	{0xb6,packet_lookup("Send Help/Tip Request",0x0009)},
	{0xc5,packet_lookup("Invalid Map (Request?)",0x0001)},
	{0xd9,packet_lookup("Spy On Client",0xffff)},
	{0xe0,packet_lookup("Bug Report (KR)",0xffff)},
	{0xe1,packet_lookup("Client Type(KR/SA)",0x0009)},
	{0xec,packet_lookup("Equip Macro (KR)",0xffff)},
	{0xed,packet_lookup("UnEquip Macro (KR)",0xffff)},
	{0xef,packet_lookup("KR/2D Client Login/Seed",0x0015)},
	{0xf8,packet_lookup("Character Creation (7.0.16.0)",0x006a)},
	{0xfa,packet_lookup("Open UO Store",0x0001)},
	{0xfb,packet_lookup("Update View Public House Contents",0x0002)},
	
	// <--------------------Bidrectional------------------------->
	{0x0c,packet_lookup("Edit Tile Data",0xffff)},
	{0x15,packet_lookup("Follow",0x0009)},
	{0x22,packet_lookup("Character Move Ack/ Resync Request",0x0003)},
	{0x2c,packet_lookup("Resurrection Menu",0x0002)},
	{0x39,packet_lookup("Remove (Group)",0x0009)},
	{0x3a,packet_lookup("Send Skills",0xffff)},
	{0x56,packet_lookup("Map Packet (cartography/treasure)",0x000b)},
	{0x66,packet_lookup("Books (Pages)",0xffff)},
	{0x6c,packet_lookup("Target Cursor Commands",0x0013)},
	{0x6f,packet_lookup("Secure Trading",0xffff)},
	{0x71,packet_lookup("Bulletin Board Messages",0xffff)},
	{0x72,packet_lookup("Request War Mode",0x0005)},
	{0x73,packet_lookup("Ping Message",0x0002)},
	{0x93,packet_lookup("Book Header (old)",0x0063)},
	{0x95,packet_lookup("Dye Window",0x0009)},
	{0x98,packet_lookup("All Names (3D Only)",0xffff)},
	{0x99,packet_lookup("Give Boat/House Placement View",0x001a)},
	{0x9a,packet_lookup("Console Entry Prompt",0xffff)},
	{0xb8,packet_lookup("Request/Character Profile",0xffff)},
	{0xbb,packet_lookup("Ultima Messenger",0x0009)},
	{0xbd,packet_lookup("Client Version",0xffff)},
	{0xbe,packet_lookup("Assist Version",0xffff)},
	{0xbf,packet_lookup("General Information Packet",0xffff)},
	{0xc2,packet_lookup("Unicode TextEntry",0xffff)},
	{0xc8,packet_lookup("Client View Range",0x0002)},
	{0xc9,packet_lookup("Get Area Server Ping (God Client)",0x0006)},
	{0xca,packet_lookup("Get User Server Ping (God Client)",0x0006)},
	{0xd0,packet_lookup("Configuration File",0xffff)},
	{0xd1,packet_lookup("Logout Status",0x0002)},
	{0xd4,packet_lookup("Book Header (New)",0xffff)},
	{0xd6,packet_lookup("Mega Cliloc",0xffff)},
	{0xd7,packet_lookup("Generic AOS Commands",0xffff)},
	{0xf1,packet_lookup("Freeshard List",0xffff)},
	
	// -----------------------Outgoing--------------------------->
	{0x11,packet_lookup("Status Bar Info",0xffff)},
	{0x16,packet_lookup("New Health Bar status update (SA)",0xffff)},
	{0x17,packet_lookup("Health Bar status update (KR)",0x000c)},
	{0x1a,packet_lookup("Object Info",0xffff)},
	{0x1b,packet_lookup("Login Confirmation",0x0020)},
	{0x1c,packet_lookup("Send Speech",0xffff)},
	{0x1d,packet_lookup("Delete Object",0x0005)},
	{0x1f,packet_lookup("Explosion",0x0008)},
	{0x20,packet_lookup("Draw Game Player",0x0013)},
	{0x21,packet_lookup("Char Move Regection",0x0008)},
	{0x23,packet_lookup("Dragging of Item",0x0017)},
	{0x24,packet_lookup("Draw Container",0x0007)},
	{0x25,packet_lookup("Add Item to Container",0x0015)},
	{0x26,packet_lookup("Kick Player",0x0005)},
	{0x27,packet_lookup("Reject Move Item Request",0x0002)},
	{0x28,packet_lookup("Drop Item Failed/Clear Square (GOD Client?)",0x0005)},
	{0x29,packet_lookup("Drop Item Approved",0x0001)},
	{0x2a,packet_lookup("Blood",0x0005)},
	{0x2b,packet_lookup("GOD Mode (GOD Client)",0x0008)},
	{0x2d,packet_lookup("Mob Attributes",0x0011)},
	{0x2e,packet_lookup("Worn Item",0x000f)},
	{0x2f,packet_lookup("Char Move Rejection",0x000a)},
	{0x30,packet_lookup("Attack OK",0x0005)},
	{0x31,packet_lookup("Attack Ended",0x0001)},
	{0x32,packet_lookup("Unknown",0x0002)},
	{0x33,packet_lookup("Pause Client",0x0002)},
	{0x36,packet_lookup("Resource Tile Data (GOD Client)",0xffff)},
	{0x3c,packet_lookup("Add Multiple Items in Comtainer",0xffff)},
	{0x3e,packet_lookup("Versions (GOD Client)",0x0025)},
	{0x3f,packet_lookup("Update Statics (GOD Client)",0xffff)},
	{0x4e,packet_lookup("Personal Light Level",0x0006)},
	{0x4f,packet_lookup("Overall Light Level",0x0002)},
	{0x53,packet_lookup("Reject Character Login",0x0002)},
	{0x54,packet_lookup("Play Sound Effect",0x000c)},
	{0x55,packet_lookup("Login Complete",0x0001)},
	{0x65,packet_lookup("Set Weather",0x0004)},
	{0x6e,packet_lookup("Character Animation",0x000e)},
	{0x70,packet_lookup("Graphical Effect",0x001c)},
	{0x74,packet_lookup("Open Buy WIndow",0xffff)},
	{0x76,packet_lookup("New subserver",0x0010)},
	{0x77,packet_lookup("Updated Player",0x0011)},
	{0x78,packet_lookup("Draw Object",0xffff)},
	{0x7c,packet_lookup("Open Dialog Box",0xffff)},
	{0x82,packet_lookup("Login Denied",0x0002)},
	{0x86,packet_lookup("Resend Characters After Delete",0x0130)},
	{0x88,packet_lookup("Open Paperdoll",0x0042)},
	{0x89,packet_lookup("Corpse Clothing",0xffff)},
	{0x8c,packet_lookup("Connect To Game Server",0x000b)},
	{0x90,packet_lookup("Map Message",0x0013)},
	{0x97,packet_lookup("Move Player",0x0002)},
	{0x9c,packet_lookup("Request Assistance",0x0035)},
	{0x9e,packet_lookup("Sell List",0xffff)},
	{0xa1,packet_lookup("Update Current Health",0x0009)},
	{0xa2,packet_lookup("Update Current Mana",0x0009)},
	{0xa3,packet_lookup("Update Current Stamina",0x0009)},
	{0xa5,packet_lookup("Open Web Browser",0xffff)},
	{0xa8,packet_lookup("Game Server List",0xffff)},
	{0xa9,packet_lookup("Characters/Starting Locations",0xffff)},
	{0xaa,packet_lookup("Allow/Refuse Attack",0x0005)},
	{0xab,packet_lookup("Gump Text Entry Dialog",0xffff)},
	{0xae,packet_lookup("Unicode Speech Message",0xffff)},
	{0xaf,packet_lookup("Display Death Action",0x000d)},
	{0xb0,packet_lookup("Send Gump Menu Dialog",0xffff)},
	{0xb2,packet_lookup("Chat Message",0xffff)},
	{0xb7,packet_lookup("Help/Tip Data",0xffff)},
	{0xb9,packet_lookup("Enable Locked Client Features",0x0005)},
	{0xba,packet_lookup("Quest Arrow",0x000a)},
	{0xbc,packet_lookup("Seasonal Information",0x0003)},
	{0xc0,packet_lookup("Graphical Effect",0x0024)},
	{0xc1,packet_lookup("Cliloc Message",0xffff)},
	{0xc4,packet_lookup("Translucent ",0x0006)},
	{0xc6,packet_lookup("Invalid Map Enable",0x0001)},
	{0xc7,packet_lookup("3d Partical Effect",0x0031)},
	{0xcb,packet_lookup("Global Queue Count",0x0007)},
	{0xcc,packet_lookup("Cliloc Message Affix",0xffff)},
	{0xd2,packet_lookup("Extended 0x20",0x0019)},
	{0xd3,packet_lookup("Extended 0x78",0xffff)},
	{0xd8,packet_lookup("Send Custom House",0xffff)},
	{0xdb,packet_lookup("Character Transfer Log",0xffff)},
	{0xdd,packet_lookup("Compressed Gump",0xffff)},
	{0xde,packet_lookup("Update Mobile Status",0xffff)},
	{0xdf,packet_lookup("Buff/Debuff System",0xffff)},
	{0xe2,packet_lookup("New Character Animation (KR)",0x000a)},
	{0xe3,packet_lookup("KR Encryption Response",0x004d)},
	{0xf0,packet_lookup("Krrios Client Special",0xffff)},
	{0xf3,packet_lookup("Object Information (SA)",0x0018)},
	{0xf5,packet_lookup("New Map Message",0x0015)}
	
	// ------------------------Unknown----------------------------
	//{0x0b,packet_lookup("NOT DEFINED",0xffff)},
	//{0x0d,packet_lookup("NOT DEFINED",0xffff)},
	//{0x0e,packet_lookup("NOT DEFINED",0xffff)},
	//{0x0f,packet_lookup("NOT DEFINED",0xffff)},
	//{0x10,packet_lookup("NOT DEFINED",0xffff)},
	//{0x18,packet_lookup("NOT DEFINED",0xffff)},
	//{0x19,packet_lookup("NOT DEFINED",0xffff)},
	//{0x3d,packet_lookup("NOT DEFINED",0xffff)},
	//{0x40,packet_lookup("NOT DEFINED",0xffff)},
	//{0x41,packet_lookup("NOT DEFINED",0xffff)},
	//{0x42,packet_lookup("NOT DEFINED",0xffff)},
	//{0x43,packet_lookup("NOT DEFINED",0xffff)},
	//{0x44,packet_lookup("NOT DEFINED",0xffff)},
	//{0x67,packet_lookup("NOT DEFINED",0xffff)},
	//{0x68,packet_lookup("NOT DEFINED",0xffff)},
	//{0x6a,packet_lookup("NOT DEFINED",0xffff)},
	//{0x6b,packet_lookup("NOT DEFINED",0xffff)},
	//{0x6d,packet_lookup("NOT DEFINED",0xffff)},
	//{0x79,packet_lookup("NOT DEFINED",0xffff)},
	//{0x7a,packet_lookup("NOT DEFINED",0xffff)},
	//{0x7b,packet_lookup("NOT DEFINED",0xffff)},
	//{0x7e,packet_lookup("NOT DEFINED",0xffff)},
	//{0x7f,packet_lookup("NOT DEFINED",0xffff)},
	//{0x81,packet_lookup("NOT DEFINED",0xffff)},
	//{0x84,packet_lookup("NOT DEFINED",0xffff)},
	//{0x85,packet_lookup("NOT DEFINED",0xffff)},
	//{0x87,packet_lookup("NOT DEFINED",0xffff)},
	//{0x8a,packet_lookup("NOT DEFINED",0xffff)},
	//{0x8b,packet_lookup("NOT DEFINED",0xffff)},
	//{0x8e,packet_lookup("NOT DEFINED",0xffff)},
	//{0x8f,packet_lookup("NOT DEFINED",0xffff)},
	//{0x92,packet_lookup("NOT DEFINED",0xffff)},
	//{0x94,packet_lookup("NOT DEFINED",0xffff)},
	//{0x96,packet_lookup("NOT DEFINED",0xffff)},
	//{0x9d,packet_lookup("NOT DEFINED",0xffff)},
	//{0xa6,packet_lookup("NOT DEFINED",0xffff)},
	//{0xa7,packet_lookup("NOT DEFINED",0xffff)},
	//{0xb4,packet_lookup("NOT DEFINED",0xffff)},
	//{0xc3,packet_lookup("NOT DEFINED",0xffff)},
	//{0xcd,packet_lookup("NOT DEFINED",0xffff)},
	//{0xce,packet_lookup("NOT DEFINED",0xffff)},
	//{0xcf,packet_lookup("NOT DEFINED",0xffff)},
	//{0xd5,packet_lookup("NOT DEFINED",0xffff)},
	//{0xda,packet_lookup("NOT DEFINED",0xffff)},
	//{0xdc,packet_lookup("NOT DEFINED",0xffff)},
	//{0xe4,packet_lookup("NOT DEFINED",0xffff)},
	//{0xe5,packet_lookup("NOT DEFINED",0xffff)},
	//{0xe6,packet_lookup("NOT DEFINED",0xffff)},
	//{0xe7,packet_lookup("NOT DEFINED",0xffff)},
	//{0xe8,packet_lookup("NOT DEFINED",0xffff)},
	//{0xe9,packet_lookup("NOT DEFINED",0xffff)},
	//{0xea,packet_lookup("NOT DEFINED",0xffff)},
	//{0xeb,packet_lookup("NOT DEFINED",0xffff)},
	//{0xee,packet_lookup("NOT DEFINED",0xffff)},
	//{0xf2,packet_lookup("NOT DEFINED",0xffff)},
	//{0xf4,packet_lookup("NOT DEFINED",0xffff)},
	//{0xf6,packet_lookup("NOT DEFINED",0xffff)},
	//{0xf7,packet_lookup("NOT DEFINED",0xffff)},
	//{0xf9,packet_lookup("NOT DEFINED",0xffff)},
	//{0xfc,packet_lookup("NOT DEFINED",0xffff)},
	//{0xfd,packet_lookup("NOT DEFINED",0xffff)},
	//{0xfe,packet_lookup("NOT DEFINED",0xffff)},
	

};

#endif /* packet_sizes_h */
